#!/usr/bin/env zsh
if [ $# -eq 0 ]; then
  echo "Usage:"
  echo "git wip (branch-name) (issue-number)"
  exit 2
fi
issue_number=''
issue_title=''
branch_name=$1
if [ $# -eq 2 ]; then
  issue_number="#$2"
  branch_name="$1/$2"
  issue_title=$(hub issue | grep $2 | xargs)
fi

git pull origin develop
git checkout -b $branch_name
git commit --allow-empty -m "[ci skip][init]$issue_number"
git push -u origin HEAD

pull_request_title="[WIP] $issue_title"
open $(echo "$pull_request_title" | hub pull-request -F -)
